export type NumericMap = Record<string, number>;
export type CalcResult = { values: Record<string, string>; formula: string };
export const finite = (value: number) => Number.isFinite(value);
export function requirePositive(values: NumericMap, keys: string[]): string | null { for (const key of keys) if (!finite(values[key]) || values[key] <= 0) return `${key} must be a finite value greater than zero.`; return null; }
export function requireNonNegative(values: NumericMap, keys: string[]): string | null { for (const key of keys) if (!finite(values[key]) || values[key] < 0) return `${key} must be finite and non-negative.`; return null; }
export function ohms(inputs: NumericMap): CalcResult | string { const { voltage, current, resistance } = inputs; const raw=[voltage,current,resistance]; if (raw.some(v=>v===Infinity||v===-Infinity)) return 'Values must be finite and non-negative.'; const known = raw.filter(v=>finite(v)).length; if (known < 2) return 'Enter any two of voltage, current, and resistance.'; if (raw.filter(finite).some(v => v < 0)) return 'Values must be finite and non-negative.'; if (voltage === 0 && current === 0) return 'Voltage and current cannot both be zero.'; let v=voltage, i=current, r=resistance; if (!finite(v)) v=i*r; if (!finite(i)) i=v/r; if (!finite(r)) r=v/i; if (![v,i,r].every(finite) || (r === 0 && v !== 0)) return 'This combination is mathematically invalid.'; return { values: { Voltage: `${v} V`, Current: `${i} A`, Resistance: `${r} Ω`, Power: `${v*i} W` }, formula: 'V = I × R; P = V × I' }; }
export function powerFactor(inputs: NumericMap): CalcResult | string { const { realPower, apparentPower }=inputs; const e=requirePositive(inputs,['apparentPower']); if (e) return e; if (!finite(realPower) || realPower < 0 || realPower > apparentPower) return 'Real power must be finite, non-negative, and no greater than apparent power.'; const pf=realPower/apparentPower; const reactive=Math.sqrt(Math.max(0, apparentPower**2-realPower**2)); return { values: { 'Power Factor': pf.toFixed(6), 'Reactive Power': `${reactive} VAR`, 'Real Power': `${realPower} W`, 'Apparent Power': `${apparentPower} VA` }, formula: 'S² = P² + Q²; PF = P ÷ S' }; }
export function transformer(inputs: NumericMap): CalcResult | string { const { primaryVoltage, secondaryVoltage, primaryTurns, secondaryTurns }=inputs; const vals=[primaryVoltage,secondaryVoltage,primaryTurns,secondaryTurns]; if (vals.filter(finite).length !== 4 || vals.some(v=>!finite(v)||v<=0)) return 'All transformer values must be finite and greater than zero.'; const ratio=primaryVoltage/secondaryVoltage; const turnsRatio=primaryTurns/secondaryTurns; if (Math.abs(ratio-turnsRatio)>Math.max(1e-9,Math.abs(ratio)*1e-6)) return 'Ideal transformer relationship mismatch: Vp/Vs must equal Np/Ns.'; return { values: { 'Turns Ratio (Np/Ns)': turnsRatio.toFixed(6), 'Voltage Ratio (Vp/Vs)': ratio.toFixed(6) }, formula: 'Vp/Vs = Np/Ns' }; }
export function threePhase(inputs: NumericMap): CalcResult | string { const { lineVoltage,current,powerFactor:pf }=inputs; const e=requirePositive(inputs,['lineVoltage','current']); if(e)return e; if(!finite(pf)||pf<=0||pf>1)return 'Power factor must be greater than zero and at most one.'; const power=Math.sqrt(3)*lineVoltage*current*pf; return { values: { 'Active Power': `${power} W`, 'Line Voltage': `${lineVoltage} V`, Current: `${current} A`, 'Power Factor': pf.toFixed(6) }, formula: 'P = √3 × VL × I × PF' }; }
export const conversions: Record<string, number> = { W:1, kW:1000, MW:1000000, V:1, kV:1000, A:1, mA:0.001, 'Ω':1, kΩ:1000 };
export function convert(value: number, from: string|number, to: string|number): CalcResult | string { const source=String(from), target=String(to); if(!finite(value)) return 'Value must be finite.'; if(!(source in conversions)||!(target in conversions)) return 'Unsupported unit.'; const groups = (u:string) => u==='W'||u==='kW'||u==='MW'?'power':u==='V'||u==='kV'?'voltage':u==='A'||u==='mA'?'current':'resistance'; if(groups(source)!==groups(target))return 'Choose units from the same measurement group.'; return { values: { Result: `${value*conversions[source]/conversions[target]} ${target}` }, formula: `${value} ${source} → ${target}` }; }
